// <auto-generated />
namespace asp.netmvcday1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Kavitha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kavitha));
        
        string IMigrationMetadata.Id
        {
            get { return "201910030520495_Kavitha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
